### ISSUE TITLE
exec: "ulimit": executable file not found in $PATH

### ISSUE THREAD

**Issue by babaloveyou** [hakluke/hakcheckurl#3]
root@ubuntu:~# hakcheckurl google.com
2020/01/14 15:18:28 exec: "ulimit": executable file not found in $PATH

**Comment by hakluke** [comment]
Hi @babaloveyou,
Apologies, this was cause by a recent PR. Please try re-installing and trying again :)

**Comment by hakluke** [comment]
Also the usage of this command should be as follows:

```
echo "http://google.com" | hakcheckurl
```

**Comment by dzhenway** [comment]
hi @hakluke 

I still got some error

`2020/01/24 13:55:10 exec: "ulimit": executable file not found in $PATH`

How to fix that? I tried reinstall but still error.

**Comment by hakluke** [comment]
Hey @dzhenway - it looks like you are using an old version. Please update.
