### ISSUE TITLE
Feature request (-t for number of threads to use)

### ISSUE THREAD

**Issue by dark-warlord14** [hakluke/hakcheckurl#6]
This is very nice. You wouldn't believe me but I was using some hacked up bash one liner to do this for me. 

`parallel -j 50 -I# 'echo "$(printf "%-100s" "#") -> $((curl -I -s -m 5 -k "#"||echo KO)|head -n 1 -)"'`

The only problem with that bash was it ate almost all memory. So thanks to you for this amazing tool.

Making the actual feature request here. 
It will be awesome if we implement number of threads with -t flag. We can make this more faster as it is in written in go. What are your thoughts on it?

**Comment by hakluke** [comment]
Done!
